name = input("Enter player name: ")
print("The sun rises on your fifth day wandering the Abyssal Fog, Veyne by your side, on your nerves as usual.")
print("Veyne: It's been so long... are we doomed to die here?")
print("{}: Stop your complaining, it's not help-".format(name))
print("Veyne: Shut up. Hear that?")
print("Though Veyne's interruption irked you, you close your eyes, listening for any signs of life.")
print("Sure enough... you hear the noise of a bustling market, faint but there.")
print("{} (thinking): Finally, I won't be alone with this smug know-it-all.".format(name))